[project]
name = "rust-python-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "torch==2.10.0+cu130",
    "torchvision==0.25.0+cu130",
]
[tool.uv]
index-url = "https://download.pytorch.org/whl/cu130"